#!/usr/bin/env bash
# =====================================================================
# Run the full replication matrix inside tmux -- survives SSH drops.
# =====================================================================
#
# Why tmux: on a plain GPU server there is no scheduler holding your job.
# Close the laptop, lose the SSH connection, and the process gets a SIGHUP
# and dies -- taking an hour of GPU work with it. tmux keeps the shell alive
# on the server, so you can detach, go home, and reattach tomorrow.
#
# Usage:
#     bash scripts/run_tmux.sh              # start the full R0-R5 matrix
#     bash scripts/run_tmux.sh R1           # just the headline run
#     tmux attach -t got                    # watch it
#     Ctrl-b then d                         # detach (job keeps running)
#     tmux kill-session -t got              # stop everything
#
# If tmux is not installed and you cannot install it, use
# `bash scripts/run_direct.sh --bg` instead -- same durability via nohup.
#
set -euo pipefail

SESSION="${SESSION:-got}"
WHICH="${1:-all}"

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

if ! command -v tmux >/dev/null 2>&1; then
    echo "ERROR: tmux not installed on this machine." >&2
    echo "       No root? Use: bash scripts/run_direct.sh --bg" >&2
    exit 1
fi

if tmux has-session -t "$SESSION" 2>/dev/null; then
    echo "Session '$SESSION' already exists. Attach with:  tmux attach -t $SESSION"
    echo "Or kill it first:                                tmux kill-session -t $SESSION"
    exit 1
fi

# ---------------------------------------------------------------------
# Knobs
# ---------------------------------------------------------------------
MODEL_ID="${MODEL_ID:-Qwen/Qwen2.5-7B-Instruct}"
BACKEND="${BACKEND:-vllm}"
LIMIT="${LIMIT:-100}"
GPU="${CUDA_VISIBLE_DEVICES:-0}"
GPU_MEM_UTIL="${GPU_MEM_UTIL:-0.60}"
ENV_NAME="${ENV_NAME:-GOTComp-cu121}"
SCHEMES="${SCHEMES:-io cot cot_sc tot got}"
STAMP="$(date +%Y%m%d_%H%M%S)"
OUT="${OUT:-results/matrix_${STAMP}}"

mkdir -p "$OUT" logs

# ---------------------------------------------------------------------
# Build the script tmux will execute.
# ---------------------------------------------------------------------
# Written to a file rather than passed inline: tmux send-keys mangles long
# quoted commands, and a file is also a record of exactly what was run.
PLAN="$OUT/plan.sh"

{
cat <<HEADER
#!/usr/bin/env bash
# Generated by run_tmux.sh on $(date). This is the exact plan that ran.
set -uo pipefail          # NOT -e: one failed run must not abort the matrix

# ---------------------------------------------------------------------
# Silence stray keystrokes for the duration of the run.
# ---------------------------------------------------------------------
# The benchmark never reads stdin, so anything typed into this pane is
# echoed by the tty and never consumed. Hold an arrow key trying to scroll
# and you get a screen full of ^[[B (Down) or ^[[A (Up), burying the output
# you actually wanted to read. Harmless to the run, but it hides results.
#
# Turn echo off while work is in progress and restore it on any exit path --
# leaving a terminal with echo off is far worse than the noise it prevents.
if [ -t 0 ]; then
    _TTY_SAVE="\$(stty -g 2>/dev/null || true)"
    restore_tty () {
        if [ -n "\${_TTY_SAVE:-}" ]; then stty "\$_TTY_SAVE" 2>/dev/null || stty sane 2>/dev/null
        else stty sane 2>/dev/null; fi
    }
    trap restore_tty EXIT INT TERM
    stty -echo 2>/dev/null || true
fi

source "\$(dirname \$(dirname \$(command -v conda)))/etc/profile.d/conda.sh"
conda activate ${ENV_NAME}
cd "${PROJECT_ROOT}"

cat <<'BANNER'
+------------------------------------------------------------------+
|  This pane is running the benchmark. Typing here does nothing.    |
|                                                                   |
|  SCROLL BACK : Ctrl-b then [      (arrows/PgUp, then q to exit)   |
|  DETACH      : Ctrl-b then d      (the run keeps going)           |
|  REATTACH    : tmux attach -t got                                 |
|                                                                   |
|  Do NOT use arrow keys outside copy mode -- they are echoed raw.  |
+------------------------------------------------------------------+
BANNER

export CUDA_VISIBLE_DEVICES=${GPU}
export HF_HOME="\${HF_HOME:-${PROJECT_ROOT}/.hf_cache}"
mkdir -p "\$HF_HOME"

COMMON="--backend ${BACKEND} --model-id ${MODEL_ID} \\
        --gpu-memory-utilization ${GPU_MEM_UTIL} --limit ${LIMIT} \\
        --temperature 1.0"

run () {   # run <tag> <extra args...>
    local tag="\$1"; shift
    echo
    echo "=============================================================="
    echo ">>> \$tag   started \$(date +%H:%M:%S)"
    echo "=============================================================="
    python scripts/run_benchmark.py \$COMMON "\$@" --out "${OUT}/\$tag" \\
        2>&1 | tee "${OUT}/\$tag.log"
    echo ">>> \$tag   finished \$(date +%H:%M:%S)"
}

SORT=data/official/sorting
SI=data/official/set_intersection
SCHEMES="${SCHEMES}"

echo "Matrix started \$(date). Output: ${OUT}"
HEADER

# --- R0: free mock check -------------------------------------------
if [ "$WHICH" = "all" ] || [ "$WHICH" = "R0" ]; then
cat <<'R0'

echo; echo "### R0 - mock sanity check (no GPU) ###"
python scripts/run_benchmark.py --task sorting --data $SORT/sorting_064.csv \
    --limit 10 --backend mock --schemes $SCHEMES --out "OUTDIR/R0" \
    2>&1 | tee "OUTDIR/R0.log"
R0
fi

# --- R1: the headline run ------------------------------------------
if [ "$WHICH" = "all" ] || [ "$WHICH" = "R1" ]; then
cat <<'R1'

run R1_sorting_64 --task sorting --data $SORT/sorting_064.csv --schemes $SCHEMES
R1
fi

# --- R2: difficulty trend ------------------------------------------
if [ "$WHICH" = "all" ] || [ "$WHICH" = "R2" ]; then
cat <<'R2'

run R2_sorting_32  --task sorting --data $SORT/sorting_032.csv --schemes $SCHEMES
run R2_sorting_128 --task sorting --data $SORT/sorting_128.csv --schemes $SCHEMES
R2
fi

# --- R3: second task -----------------------------------------------
if [ "$WHICH" = "all" ] || [ "$WHICH" = "R3" ]; then
cat <<'R3'

run R3_setint_32 --task set_intersection --data $SI/set_intersection_032.csv \
    --schemes $SCHEMES
R3
fi

# --- R4: cost/quality curve ----------------------------------------
if [ "$WHICH" = "all" ] || [ "$WHICH" = "R4" ]; then
cat <<'R4'

for k in 3 5 10; do
    run "R4_aggk_$k" --task sorting --data $SORT/sorting_064.csv \
        --schemes got --aggregation-attempts $k
done
R4
fi

# --- R5: optimum in m, plus the refinement ablation ----------------
if [ "$WHICH" = "all" ] || [ "$WHICH" = "R5" ]; then
cat <<'R5'

for m in 2 4 8; do
    run "R5_chunks_$m" --task sorting --data $SORT/sorting_064.csv \
        --schemes got --num-chunks $m
done

# Does the final corrective pass earn its tokens?
run R5_refine_off --task sorting --data $SORT/sorting_064.csv \
    --schemes got --refine-attempts 0
R5
fi

cat <<'FOOTER'

echo
echo "=============================================================="
echo "MATRIX COMPLETE"
echo "=============================================================="
python scripts/compare_to_paper.py --results "OUTDIR" || true
echo
echo "All output under: OUTDIR"
echo "Per-run logs   : OUTDIR/*.log   (readable without scrolling tmux)"

# `exec` replaces this process, so the EXIT trap will never fire -- restore
# the terminal by hand before handing the pane back to an interactive shell.
type restore_tty >/dev/null 2>&1 && restore_tty
trap - EXIT INT TERM

echo
echo "Keyboard is live again. Detach with Ctrl-b then d."
exec bash
FOOTER
} > "$PLAN"

# Substitute the output dir placeholder used inside the quoted heredocs.
sed -i "s|OUTDIR|${OUT}|g" "$PLAN"
chmod +x "$PLAN"

# ---------------------------------------------------------------------
# Launch
# ---------------------------------------------------------------------
tmux new-session -d -s "$SESSION" "bash '$PLAN'"

cat <<EOF

Started tmux session '${SESSION}' running: ${WHICH}

  Model   : ${MODEL_ID}
  GPU     : ${GPU}  (mem util ${GPU_MEM_UTIL})
  Output  : ${OUT}
  Plan    : ${PLAN}

  Watch      : tmux attach -t ${SESSION}
  Detach     : Ctrl-b then d        <- job keeps running
  Check live : tail -f ${OUT}/*.log
  Stop       : tmux kill-session -t ${SESSION}

Safe to close your laptop now.
EOF
